version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: result/latest
    ports:
      - "4000:4000"
    volumes:
      - ".:/src"
    network_mode: "host"